### ISSUE TITLE
Question about Table 7

### ISSUE THREAD

**Issue by wjczf123** [ZBWpro/PretCoTandKE#2]
The “Spearman” column retains its meaning from previous sections, signifying the average performance across seven STS benchmarks for the stated methods. 

However, this result looks like from the STS-B dataset.

**Comment by ZBWpro** [comment]
Thank you for raising this issue. Your understanding is correct, and we will correct this error later.

**Comment by wjczf123** [comment]
OK. Thanks for your reply.
